var sentences = [
  "I Love you",
  "I miss you", 
  "Soon we can cuddle again", 
  "Not that much longer...", 
  "I love you. More than anything.",
  "You are my love. My (hopefully) future husband.",
  "I will love you forever, through every high and low.",
  "You make the sky illuminate with beautiful colors, making me able to enjoy it once again.",
  "You are my moon person.",
  "You’ve taught me what unconditional love feels like, not only to feel but to receive.",
  "You mean everything to me.",
  "You are my everything.",
  "Your love has turned my life into a beautiful song, a rhythm that beats in sync with my heart.",
  "In the symphony of my life, you're the melody that brings harmony to every note.",
  "You are my star, a beautiful, bright, shining beacon in my night sky.",
  "You are everything to me.",
  "I wanna be the best partner that you ever had.",
  "I hope for my star to shine forever.",
  "I know that even when there are clouds that you are still there.",
  "You are the greatest thing that has ever happened to me.",
  "You make me smile and laugh even when I don’t want to.",
  "I love you to the moon and back and beyond infinity.",
  "I am just so happy I get to be in the same universe as you.",
  "You make me able to enjoy life once again.",
  "Our love is like a fine wine, it gets better with time.",
  "With you, every moment is a sweet serenade.",
  "You are the poetry my heart was waiting to write.",
  "Your love is the compass that guides me through life's journey.",
  "In your arms, I've found my home.",
  "I cherish every beat of your heart because they synchronize with mine.",
  "Your smile is the sunrise that brightens my darkest days.",
  "Together, we create a story more beautiful than any fairy tale.",
  "I love you not only for who you are but for who I am when I'm with you.",
  "Our love is a dance, and every step is a moment to treasure.",
  "In your eyes, I see a reflection of a love that knows no bounds.",
  "You are the melody in the soundtrack of my life.",
  "With you, every day feels like a new chapter of a love story.",
  "Our love is a masterpiece, painted with the colors of passion and affection.",
];
